# LIBS

In [68]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeRegressor

from lazypredict.Supervised import LazyRegressor

---

Rode as linhas de codigo abaixo para arrumar o dataset

# MODELANDO DATASET

In [2]:
df = pd.read_excel("data.xlsx", sheet_name="fVendas")

In [3]:
df

,nfe,data,vendedor_id,cliente_id,produto_id,valor_desconto,item_quantidade,valor_unitario
0,SO43693,2020-03-08,5,195,79,11.7902,1,167
1,SO43895,2020-03-17,5,595,79,11.0387,1,167
2,SO44100,2020-03-27,5,530,79,11.6399,1,167
3,SO44283,2020-04-04,5,165,79,8.7675,1,167
4,SO44504,2020-04-17,5,221,79,13.0594,1,167
...,...,...,...,...,...,...,...,...
54678,SO117675,2022-11-02,5,671,91,14.0175,3,75
54679,SO117675,2022-11-02,5,671,91,14.0175,3,75
54680,SO117675,2022-11-02,5,671,91,14.0175,3,75
54681,SO117675,2022-11-02,5,671,91,14.0175,3,75
54682,SO117675,2022-11-02,5,671,91,14.0175,3,75

In [4]:
df[df.nfe == "SO43693"]["valor_unitario"].sum()

1699

In [5]:
df[df.nfe == "SO117675"]["valor_unitario"].sum()

6361

In [6]:
df.columns

Index(['nfe', 'data', 'vendedor_id', 'cliente_id', 'produto_id',
       'valor_desconto', 'item_quantidade', 'valor_unitario'],
      dtype='object')

In [7]:
novo_df = {
    "nfe": [np.nan] * 3431,
    "vendedor_id": [np.nan] * 3431,
    "cliente_id": [np.nan] * 3431,
    "produto_id": [np.nan] * 3431,
    "valor_desconto": [np.nan] * 3431,
    "item_quantidade": [np.nan] * 3431,
    "valor_unitario": [np.nan] * 3431,
}

In [8]:
df.nfe.unique()

array(['SO43693', 'SO43895', 'SO44100', ..., 'SO85541', 'SO117671',
       'SO49148'], dtype=object)

In [9]:
df_2 = pd.DataFrame(novo_df)

In [10]:
df_2

,nfe,vendedor_id,cliente_id,produto_id,valor_desconto,item_quantidade,valor_unitario
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
3426,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3427,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3428,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3429,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3430,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df_2.nfe = df.nfe.unique()

In [12]:
df_2

,nfe,vendedor_id,cliente_id,produto_id,valor_desconto,item_quantidade,valor_unitario
0,SO43693,NaN,NaN,NaN,NaN,NaN,NaN
1,SO43895,NaN,NaN,NaN,NaN,NaN,NaN
2,SO44100,NaN,NaN,NaN,NaN,NaN,NaN
3,SO44283,NaN,NaN,NaN,NaN,NaN,NaN
4,SO44504,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
3426,SO47672,NaN,NaN,NaN,NaN,NaN,NaN
3427,SO49155,NaN,NaN,NaN,NaN,NaN,NaN
3428,SO85541,NaN,NaN,NaN,NaN,NaN,NaN
3429,SO117671,NaN,NaN,NaN,NaN,NaN,NaN
3430,SO49148,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
for i in range(len(df_2)):
    if df_2.nfe[i] == df.nfe.unique()[i]:
        df_2.vendedor_id[i] = df.vendedor_id[i]

/tmp/ipykernel_6870/3616286467.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2.vendedor_id[i] = df.vendedor_id[i]

In [14]:
for i in range(len(df_2)):
    if df_2.nfe[i] == df.nfe.unique()[i]:
        df_2.cliente_id[i] = df.cliente_id[i]

/tmp/ipykernel_6870/4008533701.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2.cliente_id[i] = df.cliente_id[i]

In [15]:
for i in range(len(df_2)):
    if df_2.nfe[i] == df.nfe.unique()[i]:
        df_2.produto_id[i] = df.produto_id[i]

/tmp/ipykernel_6870/638796271.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2.produto_id[i] = df.produto_id[i]

In [16]:
for i in range(len(df_2)):
    if df_2.nfe[i] == df.nfe.unique()[i]:
        df_2.valor_desconto[i] = df[df.nfe == df.nfe.unique()[i]][
            "valor_desconto"
        ].sum()

/tmp/ipykernel_6870/2789953346.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2.valor_desconto[i] = df[df.nfe == df.nfe.unique()[i]]["valor_desconto"].sum()

In [17]:
for i in range(len(df_2)):
    if df_2.nfe[i] == df.nfe.unique()[i]:
        df_2.item_quantidade[i] = df[df.nfe == df.nfe.unique()[i]][
            "item_quantidade"
        ].sum()

/tmp/ipykernel_6870/396622252.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2.item_quantidade[i] = df[df.nfe == df.nfe.unique()[i]]["item_quantidade"].sum()

In [18]:
for i in range(len(df_2)):
    if df_2.nfe[i] == df.nfe.unique()[i]:
        df_2.valor_unitario[i] = df[df.nfe == df.nfe.unique()[i]][
            "valor_unitario"
        ].sum()

/tmp/ipykernel_6870/3190352590.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2.valor_unitario[i] = df[df.nfe == df.nfe.unique()[i]]["valor_unitario"].sum()

In [19]:
df_2

,nfe,vendedor_id,cliente_id,produto_id,valor_desconto,item_quantidade,valor_unitario
0,SO43693,5.0,195.0,79.0,130.5394,12.0,1699.0
1,SO43895,5.0,595.0,79.0,168.6211,19.0,2251.0
2,SO44100,5.0,530.0,79.0,218.0913,23.0,2979.0
3,SO44283,5.0,165.0,79.0,246.7500,33.0,4250.0
4,SO44504,5.0,221.0,79.0,329.7694,35.0,3617.0
...,...,...,...,...,...,...,...
3426,SO47672,9.0,92.0,16.0,6.7950,3.0,75.0
3427,SO49155,12.0,269.0,16.0,0.0000,3.0,75.0
3428,SO85541,1.0,551.0,16.0,6.7950,6.0,150.0
3429,SO117671,11.0,411.0,16.0,0.0000,3.0,75.0
3430,SO49148,6.0,192.0,16.0,11.4975,3.0,75.0

In [20]:
df = df_2.copy()

In [21]:
df

,nfe,vendedor_id,cliente_id,produto_id,valor_desconto,item_quantidade,valor_unitario
0,SO43693,5.0,195.0,79.0,130.5394,12.0,1699.0
1,SO43895,5.0,595.0,79.0,168.6211,19.0,2251.0
2,SO44100,5.0,530.0,79.0,218.0913,23.0,2979.0
3,SO44283,5.0,165.0,79.0,246.7500,33.0,4250.0
4,SO44504,5.0,221.0,79.0,329.7694,35.0,3617.0
...,...,...,...,...,...,...,...
3426,SO47672,9.0,92.0,16.0,6.7950,3.0,75.0
3427,SO49155,12.0,269.0,16.0,0.0000,3.0,75.0
3428,SO85541,1.0,551.0,16.0,6.7950,6.0,150.0
3429,SO117671,11.0,411.0,16.0,0.0000,3.0,75.0
3430,SO49148,6.0,192.0,16.0,11.4975,3.0,75.0

In [22]:
df["valor_total"] = df["valor_unitario"] - df["valor_desconto"]

In [23]:
df

,nfe,vendedor_id,cliente_id,produto_id,valor_desconto,item_quantidade,valor_unitario,valor_total
0,SO43693,5.0,195.0,79.0,130.5394,12.0,1699.0,1568.4606
1,SO43895,5.0,595.0,79.0,168.6211,19.0,2251.0,2082.3789
2,SO44100,5.0,530.0,79.0,218.0913,23.0,2979.0,2760.9087
3,SO44283,5.0,165.0,79.0,246.7500,33.0,4250.0,4003.2500
4,SO44504,5.0,221.0,79.0,329.7694,35.0,3617.0,3287.2306
...,...,...,...,...,...,...,...,...
3426,SO47672,9.0,92.0,16.0,6.7950,3.0,75.0,68.2050
3427,SO49155,12.0,269.0,16.0,0.0000,3.0,75.0,75.0000
3428,SO85541,1.0,551.0,16.0,6.7950,6.0,150.0,143.2050
3429,SO117671,11.0,411.0,16.0,0.0000,3.0,75.0,75.0000
3430,SO49148,6.0,192.0,16.0,11.4975,3.0,75.0,63.5025

In [24]:
df.cliente_id = df.cliente_id.apply(lambda x: int(x))
df.produto_id = df.produto_id.apply(lambda x: int(x))
df.item_quantidade = df.item_quantidade.apply(lambda x: int(x))

In [25]:
df

,nfe,vendedor_id,cliente_id,produto_id,valor_desconto,item_quantidade,valor_unitario,valor_total
0,SO43693,5.0,195,79,130.5394,12,1699.0,1568.4606
1,SO43895,5.0,595,79,168.6211,19,2251.0,2082.3789
2,SO44100,5.0,530,79,218.0913,23,2979.0,2760.9087
3,SO44283,5.0,165,79,246.7500,33,4250.0,4003.2500
4,SO44504,5.0,221,79,329.7694,35,3617.0,3287.2306
...,...,...,...,...,...,...,...,...
3426,SO47672,9.0,92,16,6.7950,3,75.0,68.2050
3427,SO49155,12.0,269,16,0.0000,3,75.0,75.0000
3428,SO85541,1.0,551,16,6.7950,6,150.0,143.2050
3429,SO117671,11.0,411,16,0.0000,3,75.0,75.0000
3430,SO49148,6.0,192,16,11.4975,3,75.0,63.5025

In [26]:
df.valor_total.max()

10444.6116

In [27]:
df.valor_total.min()

31.5075

In [29]:
df.to_csv("data_cleaned.csv", sep=",", index=False)

---

# SPLIT

Rode a linha de comando abaixo para ler o dataset limpo

In [ ]:
# df = pd.read_csv("data_cleaned.csv", sep = ",")

---

In [60]:
X = df.drop(columns=["nfe", "valor_desconto", "valor_unitario", "valor_total"])
y = df["valor_total"]

In [61]:
x_train, x_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

In [62]:
depth = 5

In [63]:
model = DecisionTreeRegressor(max_depth=depth)
model = model.fit(x_train, y_train)
y_pred = model.predict(x_test)

In [64]:
y_pred

array([ 797.46534462,  913.67825217,  797.46534462,  130.75949615,
       2555.57752312,  663.09878395, 5614.66880556,  468.16132736,
       6785.13389899,  159.70625225, 3446.12897241,  468.16132736,
       2954.52438462, 4095.3446359 , 6785.13389899,  318.05587642,
       3446.12897241, 9073.65108462, 6785.13389899, 3178.67304177,
        318.05587642,  913.67825217, 7243.64378113, 3223.30415143,
        318.05587642, 7243.64378113,  913.67825217,  468.16132736,
        159.70625225, 7243.64378113, 1990.07021226, 1403.07548636,
        468.16132736,  130.75949615, 1990.07021226, 3178.67304177,
       7243.64378113, 2954.52438462, 1403.07548636, 2555.57752312,
       1403.07548636, 2594.1634    , 3178.67304177,  159.70625225,
       4940.14255   , 1403.07548636,  797.46534462, 1051.00527252,
       1403.07548636,  663.09878395,  159.70625225,  468.16132736,
        130.75949615, 4494.64855362,  318.05587642, 2555.57752312,
        130.75949615, 5614.66880556, 1403.07548636, 1403.07548636,
       5927.90985926,  663.09878395,  663.09878395, 2594.1634    ,
       4494.64855362,  159.70625225, 5614.66880556,  318.05587642,
       2621.09176667, 3178.67304177, 2299.46322727,  159.70625225,
        797.46534462, 7243.64378113, 4940.14255   , 3446.12897241,
       4494.64855362, 4494.64855362, 1403.07548636,  130.75949615,
       3446.12897241, 3446.12897241, 1403.07548636,  318.05587642,
       1403.07548636, 1403.07548636,  318.05587642, 3446.12897241,
       4095.3446359 , 5927.90985926, 2555.57752312, 3223.30415143,
        468.16132736,  468.16132736, 4494.64855362, 4494.64855362,
       3815.07870185,  318.05587642,  318.05587642,  663.09878395,
        318.05587642, 2555.57752312,  318.05587642, 4494.64855362,
       7243.64378113, 4494.64855362,  468.16132736,  318.05587642,
       2555.57752312, 6785.13389899, 3223.30415143,  468.16132736,
       1737.08472899, 3815.07870185, 2299.46322727, 7243.64378113,
       4494.64855362, 2555.57752312, 3178.67304177,  318.05587642,
       1737.08472899,  468.16132736, 1737.08472899,  130.75949615,
        468.16132736, 1403.07548636,  130.75949615, 1403.07548636,
       6785.13389899, 5614.66880556,  318.05587642,  468.16132736,
        318.05587642,  159.70625225, 3223.30415143, 4494.64855362,
       1051.00527252,  318.05587642,  130.75949615, 6785.13389899,
       3223.30415143, 1139.88052222, 3815.07870185,  318.05587642,
       5927.90985926, 4494.64855362,  159.70625225,  130.75949615,
        318.05587642, 6785.13389899,  468.16132736,  159.70625225,
        159.70625225, 7243.64378113, 1403.07548636, 2555.57752312,
       1051.00527252, 7243.64378113, 7243.64378113,  130.75949615,
       5927.90985926, 4494.64855362, 1051.00527252,  130.75949615,
        318.05587642, 5927.90985926,  468.16132736, 5927.90985926,
        318.05587642, 2555.57752312, 2555.57752312,  159.70625225,
        159.70625225, 5927.90985926, 3178.67304177, 4494.64855362,
       1403.07548636,  159.70625225, 1737.08472899,  797.46534462,
        130.75949615,  468.16132736,  318.05587642, 2555.57752312,
       3223.30415143,  159.70625225, 1051.00527252,  318.05587642,
        468.16132736,  130.75949615, 7243.64378113, 1403.07548636,
       6785.13389899,  318.05587642, 1990.07021226, 1051.00527252,
        159.70625225,  130.75949615, 4494.64855362,  318.05587642,
        318.05587642, 1990.07021226, 2594.1634    ,  318.05587642,
        468.16132736, 1403.07548636, 3178.67304177, 2555.57752312,
       3446.12897241, 3446.12897241, 3223.30415143, 4494.64855362,
       1051.00527252,  159.70625225, 1990.07021226,  318.05587642,
       1737.08472899,  159.70625225, 7243.64378113,  468.16132736,
       1737.08472899, 6785.13389899,  159.70625225,  913.67825217,
       5927.90985926,  913.67825217,  318.05587642, 1403.07548636,
        318.05587642, 1990.07021226, 2954.52438462, 3178.67304177,
       2555.57752312,  318.05587642, 7243.64378113, 1737.08472899,
       5927.90985926,  318.05587642, 1403.07548636, 1051.00527252,
       1737.08472899, 9073.65108462, 1051.00527252, 4494.64855362,
        663.09878395,  159.70625225, 1051.00527252, 1403.07548636,
       6785.13389899, 6785.13389899, 5927.90985926, 5927.90985926,
       6785.13389899, 2555.57752312,  468.16132736, 4494.64855362,
       1990.07021226, 3815.07870185, 3446.12897241,  130.75949615,
       4494.64855362, 4494.64855362, 3178.67304177,  318.05587642,
       1403.07548636,  318.05587642,  663.09878395, 6785.13389899,
       2594.1634    , 5927.90985926,  318.05587642, 1403.07548636,
        130.75949615,  663.09878395,  468.16132736, 1403.07548636,
        130.75949615, 3223.30415143,  318.05587642,  159.70625225,
       1051.00527252, 2594.1634    , 2555.57752312, 1051.00527252,
        130.75949615,  468.16132736, 7243.64378113, 2299.46322727,
       4494.64855362, 4494.64855362, 4494.64855362,  159.70625225,
       3815.07870185, 1990.07021226, 3815.07870185, 1403.07548636,
       6785.13389899,  318.05587642, 3223.30415143, 3446.12897241,
       3446.12897241, 4494.64855362, 2954.52438462, 1051.00527252,
       1139.88052222,  130.75949615,  468.16132736, 3446.12897241,
       1990.07021226,  913.67825217, 1403.07548636, 2555.57752312,
        130.75949615, 5614.66880556, 5614.66880556, 4095.3446359 ,
       1051.00527252, 1990.07021226, 6785.13389899, 5614.66880556,
        159.70625225, 7243.64378113, 4494.64855362, 3223.30415143,
       1403.07548636,  468.16132736,  318.05587642, 1403.07548636,
       1051.00527252, 4940.14255   ,  130.75949615, 1051.00527252,
       1051.00527252, 5614.66880556, 1403.07548636,  663.09878395,
        159.70625225, 4494.64855362, 1051.00527252, 6785.13389899,
       4494.64855362, 6785.13389899,  913.67825217, 3815.07870185,
        468.16132736,  468.16132736, 1051.00527252, 2555.57752312,
       1051.00527252,  468.16132736,  797.46534462,  468.16132736,
       3223.30415143,  130.75949615,  159.70625225, 1737.08472899,
       3446.12897241,  130.75949615, 1403.07548636,  797.46534462,
        318.05587642, 1403.07548636, 4494.64855362, 3446.12897241,
        318.05587642, 1737.08472899, 3815.07870185, 1990.07021226,
       1403.07548636, 4494.64855362, 4494.64855362,  130.75949615,
       5614.66880556, 1051.00527252, 5927.90985926, 3223.30415143,
       6764.835275  , 1051.00527252, 1737.08472899,  130.75949615,
       4095.3446359 ,  159.70625225, 1990.07021226, 5614.66880556,
        318.05587642, 4494.64855362, 7243.64378113, 4494.64855362,
       3446.12897241,  468.16132736, 1990.07021226, 1403.07548636,
        913.67825217, 7243.64378113, 1403.07548636, 1403.07548636,
       5614.66880556, 3446.12897241, 6785.13389899, 4095.3446359 ,
        318.05587642, 2555.57752312, 5614.66880556,  130.75949615,
        663.09878395,  130.75949615, 7243.64378113, 7243.64378113,
       1051.00527252,  797.46534462, 4494.64855362, 4494.64855362,
       1990.07021226, 3178.67304177, 4494.64855362,  318.05587642,
        318.05587642, 1403.07548636, 6785.13389899, 1403.07548636,
       6785.13389899, 4494.64855362, 1403.07548636, 7243.64378113,
        159.70625225, 4494.64855362, 5927.90985926, 2555.57752312,
        318.05587642, 4494.64855362,  159.70625225,  130.75949615,
        663.09878395,  797.46534462, 3815.07870185, 1737.08472899,
       1990.07021226, 3178.67304177, 4494.64855362,  468.16132736,
        159.70625225, 1403.07548636, 1051.00527252, 6785.13389899,
       1051.00527252,  159.70625225,  468.16132736,  159.70625225,
        797.46534462,  468.16132736, 1403.07548636, 1990.07021226,
       2594.1634    , 2299.46322727, 2555.57752312,  663.09878395,
       1051.00527252, 6785.13389899, 1990.07021226,  159.70625225,
       1990.07021226, 3223.30415143, 4494.64855362,  318.05587642,
       4494.64855362,  663.09878395, 1403.07548636,  318.05587642,
       1139.88052222,  913.67825217, 2555.57752312, 3446.12897241,
       1403.07548636,  130.75949615,  913.67825217, 1990.07021226,
       4494.64855362,  130.75949615,  913.67825217, 2555.57752312,
        797.46534462, 1403.07548636, 5614.66880556, 1051.00527252,
       4494.64855362, 1051.00527252, 1737.08472899,  468.16132736,
        130.75949615,  797.46534462, 2621.09176667, 2594.1634    ,
       1051.00527252,  663.09878395, 6785.13389899, 1990.07021226,
        913.67825217, 3178.67304177, 3815.07870185, 2555.57752312,
       1990.07021226,  468.16132736,  318.05587642, 1403.07548636,
        468.16132736, 3223.30415143,  159.70625225, 4494.64855362,
        318.05587642,  318.05587642, 5927.90985926, 3223.30415143,
        130.75949615,  318.05587642, 5614.66880556, 3815.07870185,
        468.16132736, 1051.00527252,  318.05587642, 5614.66880556,
       3446.12897241,  913.67825217,  130.75949615,  468.16132736,
        159.70625225,  159.70625225, 6785.13389899, 1403.07548636,
       6785.13389899,  130.75949615,  318.05587642, 1403.07548636,
       7243.64378113, 4494.64855362, 3446.12897241,  130.75949615,
       1051.00527252, 5927.90985926, 4494.64855362, 3223.30415143,
        468.16132736, 7243.64378113,  797.46534462, 3815.07870185,
       1403.07548636, 3178.67304177, 2555.57752312, 3223.30415143,
        663.09878395, 1737.08472899, 3178.67304177,  159.70625225,
        468.16132736, 4494.64855362, 1403.07548636, 9073.65108462,
        318.05587642,  797.46534462, 2299.46322727, 5614.66880556,
       4095.3446359 ,  468.16132736,  130.75949615,  130.75949615,
       1737.08472899, 4494.64855362,  318.05587642, 1403.07548636,
       4494.64855362, 1737.08472899,  318.05587642, 4494.64855362,
        913.67825217, 1403.07548636,  468.16132736, 5614.66880556,
       5614.66880556, 1990.07021226, 3446.12897241, 1737.08472899,
       1051.00527252,  159.70625225,  159.70625225,  318.05587642,
       4095.3446359 ,  663.09878395,  130.75949615,  159.70625225,
       3223.30415143,  318.05587642,  130.75949615,  130.75949615,
       1139.88052222,  130.75949615, 2555.57752312,  130.75949615,
       1403.07548636, 4494.64855362,  913.67825217,  130.75949615,
       7243.64378113,  318.05587642, 4095.3446359 ,  130.75949615,
       5614.66880556,  130.75949615,  797.46534462, 4494.64855362,
       6785.13389899,  159.70625225,  468.16132736, 4494.64855362,
       1051.00527252, 3815.07870185,  318.05587642,  663.09878395,
       7243.64378113,  468.16132736, 5927.90985926,  318.05587642,
        468.16132736, 3815.07870185,  318.05587642,  663.09878395,
        159.70625225,  159.70625225, 2555.57752312,  663.09878395,
       1990.07021226,  318.05587642, 5927.90985926,  159.70625225,
        318.05587642,  159.70625225,  468.16132736, 1737.08472899,
       7243.64378113, 7243.64378113, 1737.08472899,  318.05587642,
       3178.67304177, 2555.57752312,  468.16132736, 2954.52438462,
       4494.64855362,  318.05587642, 1403.07548636,  159.70625225,
       4494.64855362, 1051.00527252, 7243.64378113,  318.05587642,
        159.70625225, 1139.88052222, 5927.90985926, 1403.07548636,
       1990.07021226, 4494.64855362, 6785.13389899,  663.09878395,
        468.16132736,  797.46534462, 1737.08472899,  468.16132736,
       1403.07548636, 4494.64855362,  130.75949615,  797.46534462,
       1403.07548636,  318.05587642,  130.75949615, 6785.13389899,
       4494.64855362,  318.05587642, 5927.90985926, 7243.64378113,
       5614.66880556, 5614.66880556,  159.70625225,  797.46534462,
        130.75949615, 1403.07548636, 1403.07548636,  159.70625225,
       3223.30415143, 1403.07548636,  159.70625225,  663.09878395,
        797.46534462, 5614.66880556,  318.05587642, 1139.88052222,
        663.09878395,  468.16132736,  130.75949615, 1403.07548636,
       5614.66880556,  663.09878395, 4095.3446359 , 1990.07021226,
       1139.88052222,  797.46534462, 4494.64855362,  318.05587642,
        318.05587642,  797.46534462,  318.05587642, 5614.66880556,
        159.70625225,  468.16132736,  130.75949615, 1403.07548636,
        468.16132736,  159.70625225,  159.70625225, 6785.13389899,
        663.09878395, 4095.3446359 , 1403.07548636,  159.70625225,
       3178.67304177, 2555.57752312, 1990.07021226,  913.67825217,
        130.75949615, 6785.13389899,  318.05587642, 1139.88052222,
       1403.07548636, 1051.00527252, 4494.64855362, 1403.07548636,
       5614.66880556, 2555.57752312,  318.05587642,  159.70625225,
       4494.64855362,  318.05587642,  468.16132736, 1051.00527252,
        797.46534462,  130.75949615,  913.67825217, 7243.64378113,
        159.70625225, 5614.66880556,  130.75949615, 7243.64378113,
       1051.00527252, 1990.07021226, 4494.64855362, 5614.66880556,
       2555.57752312, 3223.30415143, 1990.07021226, 5927.90985926,
       3815.07870185, 1990.07021226,  663.09878395, 6785.13389899,
        159.70625225,  130.75949615, 6785.13389899, 1403.07548636,
       1990.07021226,  663.09878395,  130.75949615,  663.09878395,
       2555.57752312, 1403.07548636, 7243.64378113,  318.05587642,
        468.16132736,  913.67825217, 1403.07548636, 3178.67304177,
        318.05587642,  913.67825217, 2555.57752312, 4494.64855362,
       3223.30415143, 3446.12897241, 3446.12897241, 1403.07548636,
       2555.57752312,  318.05587642,  468.16132736, 1403.07548636,
       3446.12897241, 3815.07870185, 2555.57752312, 4494.64855362,
        663.09878395, 3223.30415143, 1051.00527252, 4494.64855362,
        318.05587642, 2555.57752312, 1403.07548636, 1139.88052222,
        130.75949615, 1737.08472899,  159.70625225, 7243.64378113,
       1737.08472899, 1737.08472899, 6785.13389899,  130.75949615,
       1051.00527252, 3178.67304177, 2299.46322727, 1051.00527252,
        468.16132736,  159.70625225,  663.09878395, 4494.64855362,
       3446.12897241, 4494.64855362,  913.67825217, 7243.64378113,
       5614.66880556,  318.05587642, 1403.07548636, 1990.07021226,
        318.05587642, 4940.14255   , 7243.64378113, 4494.64855362,
       2555.57752312, 1990.07021226, 5614.66880556, 1051.00527252,
       3446.12897241, 1403.07548636, 1990.07021226,  130.75949615,
       2594.1634    , 9073.65108462,  663.09878395,  468.16132736,
        130.75949615, 1990.07021226, 1737.08472899, 4494.64855362,
        159.70625225, 1990.07021226, 2954.52438462, 1403.07548636,
        797.46534462, 1737.08472899, 2555.57752312, 1051.00527252,
       1051.00527252, 7243.64378113,  468.16132736,  159.70625225,
        318.05587642,  468.16132736])

In [67]:
df_temp = pd.DataFrame({"Real": y_test, "Predict": y_pred})
df_temp.sample(5)

display(df_temp.sample(5))

           Real      Predict
1181  1747.8470  1990.070212
3265   860.2548   663.098784
1268  1041.2136  1051.005273
2334   495.2632  1051.005273
3338   125.1000   159.706252

In [66]:
acc = model.score(x_test, y_test)
print(f"Model Accuracy = {acc:.2%}")

Model Accuracy = 94.31%

---

Lazy

In [69]:
reg = LazyRegressor(verbose=0, ignore_warnings=False, custom_metric=None)
models, predictions = reg.fit(x_train, x_test, y_train, y_test)

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 42/42 [05:30<00:00,  7.86s/it]

In [70]:
models

,Adjusted R-Squared,R-Squared,RMSE,Time Taken
Model,,,,
LassoLarsCV,0.95,0.95,517.08,0.03
LarsCV,0.95,0.95,517.08,0.02
LassoCV,0.95,0.95,517.10,0.09
LassoLarsIC,0.95,0.95,517.31,0.04
OrthogonalMatchingPursuitCV,0.95,0.95,517.32,0.02
Lasso,0.95,0.95,517.38,0.01
Ridge,0.95,0.95,517.46,0.01
BayesianRidge,0.95,0.95,517.49,0.10
RidgeCV,0.95,0.95,517.49,0.01
LinearRegression,0.95,0.95,517.49,0.01
TransformedTargetRegressor,0.95,0.95,517.49,0.01
Lars,0.95,0.95,517.49,0.02
SGDRegressor,0.95,0.95,517.50,0.01
OrthogonalMatchingPursuit,0.95,0.95,518.15,0.01
HuberRegressor,0.95,0.95,518.46,0.04
PassiveAggressiveRegressor,0.95,0.95,519.08,0.01
LassoLars,0.95,0.95,519.12,0.02
GradientBoostingRegressor,0.95,0.95,521.13,0.19
RANSACRegressor,0.95,0.95,521.87,0.03
LGBMRegressor,0.94,0.94,539.70,0.16
RandomForestRegressor,0.94,0.94,542.49,0.51
AdaBoostRegressor,0.94,0.94,542.93,0.07
HistGradientBoostingRegressor,0.94,0.94,544.59,0.37
BaggingRegressor,0.94,0.94,563.97,0.06
KNeighborsRegressor,0.93,0.93,583.01,0.02
XGBRegressor,0.93,0.93,591.24,0.25
ExtraTreesRegressor,0.93,0.93,598.34,0.41
ExtraTreeRegressor,0.90,0.90,710.82,0.05
DecisionTreeRegressor,0.89,0.89,738.29,0.02
ElasticNet,0.85,0.85,885.84,0.02
PoissonRegressor,0.73,0.73,1173.48,0.22
TweedieRegressor,0.72,0.72,1197.16,0.15
GammaRegressor,0.67,0.67,1297.22,0.13
LinearSVR,0.56,0.57,1492.18,0.01
ElasticNetCV,0.53,0.53,1548.80,0.14
MLPRegressor,0.47,0.47,1640.05,2.41
KernelRidge,0.08,0.09,2162.25,0.46
NuSVR,0.04,0.05,2208.75,0.30
DummyRegressor,-0.02,-0.01,2275.32,0.01
SVR,-0.06,-0.05,2323.72,0.37
QuantileRegressor,-0.22,-0.21,2492.81,322.21
GaussianProcessRegressor,-1071.41,-1066.41,73927.85,1.07

In [71]:
predictions

,Adjusted R-Squared,R-Squared,RMSE,Time Taken
Model,,,,
LassoLarsCV,0.95,0.95,517.08,0.03
LarsCV,0.95,0.95,517.08,0.02
LassoCV,0.95,0.95,517.10,0.09
LassoLarsIC,0.95,0.95,517.31,0.04
OrthogonalMatchingPursuitCV,0.95,0.95,517.32,0.02
Lasso,0.95,0.95,517.38,0.01
Ridge,0.95,0.95,517.46,0.01
BayesianRidge,0.95,0.95,517.49,0.10
RidgeCV,0.95,0.95,517.49,0.01
LinearRegression,0.95,0.95,517.49,0.01
TransformedTargetRegressor,0.95,0.95,517.49,0.01
Lars,0.95,0.95,517.49,0.02
SGDRegressor,0.95,0.95,517.50,0.01
OrthogonalMatchingPursuit,0.95,0.95,518.15,0.01
HuberRegressor,0.95,0.95,518.46,0.04
PassiveAggressiveRegressor,0.95,0.95,519.08,0.01
LassoLars,0.95,0.95,519.12,0.02
GradientBoostingRegressor,0.95,0.95,521.13,0.19
RANSACRegressor,0.95,0.95,521.87,0.03
LGBMRegressor,0.94,0.94,539.70,0.16
RandomForestRegressor,0.94,0.94,542.49,0.51
AdaBoostRegressor,0.94,0.94,542.93,0.07
HistGradientBoostingRegressor,0.94,0.94,544.59,0.37
BaggingRegressor,0.94,0.94,563.97,0.06
KNeighborsRegressor,0.93,0.93,583.01,0.02
XGBRegressor,0.93,0.93,591.24,0.25
ExtraTreesRegressor,0.93,0.93,598.34,0.41
ExtraTreeRegressor,0.90,0.90,710.82,0.05
DecisionTreeRegressor,0.89,0.89,738.29,0.02
ElasticNet,0.85,0.85,885.84,0.02
PoissonRegressor,0.73,0.73,1173.48,0.22
TweedieRegressor,0.72,0.72,1197.16,0.15
GammaRegressor,0.67,0.67,1297.22,0.13
LinearSVR,0.56,0.57,1492.18,0.01
ElasticNetCV,0.53,0.53,1548.80,0.14
MLPRegressor,0.47,0.47,1640.05,2.41
KernelRidge,0.08,0.09,2162.25,0.46
NuSVR,0.04,0.05,2208.75,0.30
DummyRegressor,-0.02,-0.01,2275.32,0.01
SVR,-0.06,-0.05,2323.72,0.37
QuantileRegressor,-0.22,-0.21,2492.81,322.21
GaussianProcessRegressor,-1071.41,-1066.41,73927.85,1.07